export enum ROLES {
  SOPORTE = 'SOPORTE',
  ADMINISTRADOR = 'ADMINISTRADOR',
}

export enum ESTADOS {
  ABIERTO = 'ABIERTO',
  EN_PROCESO = 'EN PROCESO',
  CERRADO='CERRADO',
}


// OPCIONES DE ESTABLECIMIENTO
export enum INSTITUCION {
  Msp = "MSP",
  Snai = "SNAI",
}


// OPCIONES DE DISTRITOS

export enum PROVINCIAS {
  COTOPAXI = 'COTOPAXI',
  CHIMBORAZO = 'CHIMBORAZO',
  PASTAZA = 'PASTAZA',
  TUNGURAHUA = 'TUNGURAHUA',
}

// OPCIONES DE LA ENCUESTA DE SATISFACCION
export enum SATISFACCION {
 N_S = 'NADA SATISFACTORIO',
 P_S = 'POCO SATISFACTORIO',
 S = 'SATISFACTORIO',
 M_S = 'MUY SATISFACTORIO',
}

export enum OPORTUNO {
 SI = 'SI',
 NO = 'NO',
}

export enum S_PROBLEMA {
 SI = 'SI',
 NO = 'NO',
}



