export enum ROLES {
  BASIC = 'BASICO',
  SISTEM = 'SISTEMAS',
  ADMIN = 'ADMINISTRADOR',
}

export enum ESTADOS {
  NUEVO = 'NUEVO',
  ESPERA = 'EN PROCESO',
  RESUELTO = 'FINALIZADO',
}


// OPCIONES DE PERFILES DE USUARIOS
export enum SEXO {
  MASCULINO = 'MASCULINO',
  FEMENINO = 'FEMENINO',
}

export enum ETNIA {
  AFROECUATORIANO = 'AFROECUATORIANO',
  BLANCO = 'BLANCO',
  INDIGENA = 'INDIGENA',
  MESTIZO = 'MESTIZO',
  MONTUBIO = 'MONTUBIO',
  OTROS = 'OTROS',
}

export enum N_INTRUCCION {
  SECUNDARIA = 'SECUNDARIA',
  BACHILLERATO = 'BACHILLERATO',
  TECNOLÓGICO = 'TECNOLÓGICO',
  TERCER = 'TERCER NIVEL',
  CUARTO = 'CUARTO NIVEL',
}

export enum R_LABORAL {
  SERVICIO = 'SERVICIO CIVIL PUBLICO (LOSEP)',
  CODIGO = 'CÓDIGO DEL TRABAJO',
}

export enum M_LABORAL {
  CONTRATOI = 'CONTRATO INDEFINIDO',
  CONTRATOC = 'CONTRATO COLECTIVO',
  CONTRATOO = 'CONTRATO OCACIONALES',
  CONTRATOS = 'CONTRATO SERVICIO SOCIAL SALUD',
  DEVENGANTES = 'DEVENGANTES DE BECAS LOSEP',
  NOMBRAMIENTO = 'NOMBRAMIENTO',
}

export enum NOMBRAMIENTO {
  DEFINITIVO = 'DEFINITIVO',
  PROVICIONAL = 'PROVICIONAL',
}

// OPCIONES DE ESTABLECIMIENTO
export enum INSTITUCION {
  Msp = "MSP",
  Snai = "SNAI",
}


// OPCIONES DE DISTRITOS

export enum PROVINCIAS {
  COTOPAXI = 'COTOPAXI',
  CHIMBORAZO = 'CHIMBORAZO',
  PASTAZA = 'PASTAZA',
  TUNGURAHUA = 'TUNGURAHUA',
}

// OPCIONES DE LA ENCUESTA DE SATISFACCION
export enum SATISFACCION {
 I = 'INSATISFECHO',
 A_S = 'ALGO SATISFECHO',
 S = 'SATISFECHO',
 M_S = 'MUY SATISFECHO',
 E_S = 'EXTREMADAMENTE SATISFECHO',

}



